### ISSUE TITLE
Second Sonar Build

### ISSUE THREAD

**Issue by kiview** [Linfar/TeamCity.SonarQubePlugin#12]
When having 2 sonar build steps inside the same build configuration, the second build step does not run sonar with the specified connection parameters, so sonar uses the default h2 database connection (which might not work).

**Comment by atrwsr** [comment]
It tries also to use the default sonarqube server : 'localhost:9000' even if I'm specifying the path to my sonar server !

**Comment by kiview** [comment]
Yes, it doesn't use any values from the connection parameters.

**Comment by Linfar** [comment]
Could you please describe why do you need to run sonar analysis twicely?

**Comment by kiview** [comment]
For example when I want to run the analysis for multiple profiles (which means multiple projects in Sonar).

**Comment by Linfar** [comment]
Fixed. Please update the plugin - https://teamcity.jetbrains.com/repository/download/TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin_Build/431355:id/sonar-plugin.zip
