### ISSUE TITLE
Capacity to manage (edit/remove) only by admin

### ISSUE THREAD

**Issue by axel3rd** [Linfar/TeamCity.SonarQubePlugin#14]
Hi,

The SonarQube plugin is great to manage a central instance chain of TeamCity <-> SonarQube (avoid  *public credentials* in ``sonar-project.properties``, ...).

But currently, anybody could create and **remove/edit** a SonarQube server configuration.
For a central TeamCity instance with many users, it is dangerous. Anybody could delete an *admin SonarQube configuration*;

Could a option ``Manageable by :`` created, with values ``All`` (default) / ``System administrator`` ?
Or use the [TeamCity Persmission](https://confluence.jetbrains.com/display/TCD8/Role+and+Permission) ?

Thanks in advance.
Best regards.

**Comment by Linfar** [comment]
Fixed by @axel3rd
